### ISSUE TITLE
Request: /topskulls be able to be used on skulls that are on armor stands

### ISSUE THREAD

**Issue by IITFA** [TopIn-MC/TopIn#23]
A long time ago, I had a plugin that allows me to create a "Hall of Heros" with multiple armor stands. Each stand was posed in different manners and had heads that would update based on top skills. The TopIn plugin seems to do everything needed but when trying to test it with armor stands, of course, it would not work.

**Comment by HSGamer** [comment]
An addon will be released
https://github.com/TopIn-MC/TopArmorStand
